env:
  browser: true
  jquery: true
  node: true
  es6: true

globals:
  angular: true

extends:
  - 'eslint:recommended'
  - prettier

plugins:
  - import

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    modules: true

rules:
  no-control-regex: off
  no-empty: warn
  no-empty-function: warn
  no-useless-escape: off
  import/order: error
  no-console: off
