version: "2"
linters:
  default: none
  enable:
    - forbidigo
  settings:
    forbidigo:
      forbid:
        - pattern: ^dataservices.DataStore.(EdgeGroup|EdgeJob|EdgeStack|EndpointRelation|Endpoint|GitCredential|Registry|ResourceControl|Role|Settings|Snapshot|SSLSettings|Stack|Tag|User)$
          msg: Use a transaction instead
      analyze-types: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - forbidigo
