version: '2'
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - forbidigo
  settings:
    forbidigo:
      forbid:
        - pattern: ^dataservices.DataStore.(EdgeGroup|EdgeJob|EdgeStack|EndpointRelation|Endpoint|GitCredential|Registry|ResourceControl|Role|Settings|Snapshot|SSLSettings|Stack|Tag|User)$
          msg: Use a transaction instead
        - pattern: ^(filepath|path)\.Join$
          msg: Use filesystem.JoinPaths() from github.com/portainer/portainer/api/filesystem to prevent path traversal attacks
      analyze-types: true
