body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, make sure it hasn't been already asked and answered. You can search our [discussions](https://github.com/orgs/portainer/discussions) and [bug reports](https://github.com/portainer/portainer/issues) in GitHub.  Also, be sure to check our [knowledge base](https://portal.portainer.io/knowledge) and [documentation](https://docs.portainer.io/) first.

  - type: textarea
    attributes:
      label: Ask a Question!
    validations:
      required: true
