blank_issues_enabled: false
contact_links:
  - name: Portainer Business Edition - Get 5 nodes free
    url: https://portainer.io/pricing/take5 
    about: Portainer Business Edition has more features, more support and you can now get 5 nodes free for as long as you want.
