blank_issues_enabled: false
contact_links:
  - name: Portainer Business Edition - Get 3 nodes free
    url: https://www.portainer.io/take-3 
    about: Portainer Business Edition has more features, more support and you can now get 3 nodes free for as long as you want.
