export const STATEOBJECT = {
  LOCAL_STORAGE_MEMORY: {},
  USER_TOKENS: [],
  ACTIVE_ENDPOINT_ID: '',
  ACTIVE_ENDPOINT_TYPE: '',
  ACTIVE_SWARM_ID: '',
  ACTIVE_RESOURCE: '',
  USER_RESOURCES: [],
};
