name: Test Frontend
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test:client
